theme: jekyll-theme-modernist
title: Intro to Programming Nanodegree
description: Mark Soro projects website for Introduction to Programming Nanodegree
author: Mark Soro
show_downloads: false
image: https://confirm.udacity.com/HGL2D6QN
google_analytics: G-EKQ0YXQRK1
plugins:
  - jemoji
  - jekyll-seo-tag
