theme: jekyll-theme-cayman
title: Intro to Programming Nanodegree
description: Mark Soro project website for Introduction to Programming Nanodegree
author: Mark Soro
show_downloads: false
image: https://confirm.udacity.com/HGL2D6QN
google_analytics:
plugins:
  - jemoji
  - jekyll-seo-tag
